/**
 * Guest Session Management
 *
 * Manages the access token for guest users stored in localStorage.
 * This token is:
 * - Generated by the backend when a guest creates an appointment
 * - Stored in localStorage for device-bound sessions
 * - Used to authenticate guest requests (lookup, cancel)
 *
 * Security notes:
 * - Token is UUID v4 (128 bits of entropy) - impossible to guess
 * - Token is only valid on the device where it was saved
 * - Clearing browser data loses access to appointments
 */

const GUEST_TOKEN_KEY = "gold_mustache_guest_token";

/**
 * Check if we're in a browser environment
 */
function isBrowser(): boolean {
  return typeof window !== "undefined" && typeof localStorage !== "undefined";
}

/**
 * Get the guest access token from localStorage
 * @returns The access token or null if not found
 */
export function getGuestToken(): string | null {
  if (!isBrowser()) return null;

  try {
    return localStorage.getItem(GUEST_TOKEN_KEY);
  } catch {
    // Handle cases where localStorage is disabled or throws
    console.warn("Unable to access localStorage for guest token");
    return null;
  }
}

/**
 * Save the guest access token to localStorage
 * @param token The access token to save
 */
export function setGuestToken(token: string): void {
  if (!isBrowser()) return;

  try {
    localStorage.setItem(GUEST_TOKEN_KEY, token);
  } catch {
    console.warn("Unable to save guest token to localStorage");
  }
}

/**
 * Remove the guest access token from localStorage
 */
export function clearGuestToken(): void {
  if (!isBrowser()) return;

  try {
    localStorage.removeItem(GUEST_TOKEN_KEY);
  } catch {
    console.warn("Unable to clear guest token from localStorage");
  }
}

/**
 * Check if a guest token exists in localStorage
 * @returns True if a token exists
 */
export function hasGuestToken(): boolean {
  return getGuestToken() !== null;
}
