export const LOYALTY_CONFIG = {
  POINTS_PER_CURRENCY: 10,
  CURRENCY_UNIT: 10,
  FIRST_APPOINTMENT_BONUS: 50,
  BIRTHDAY_BONUS: 100,
  REFERRAL_BONUS: 150,
  REVIEW_BONUS: 30,
  CHECKIN_BONUS: 20,
  TIERS: {
    BRONZE: { min: 0, bonus: 0 },
    SILVER: { min: 500, bonus: 0.1 },
    GOLD: { min: 1500, bonus: 0.2 },
    DIAMOND: { min: 3000, bonus: 0.3 },
  },
  POINTS_EXPIRY_MONTHS: 12,
  EXPIRY_WARNING_DAYS: 30,
  REDEMPTION_VALIDITY_DAYS: 30,
  REDEMPTION_CODE_LENGTH: 6,
};
